version: '3.8'

services:
  mysql-db:
    image: mysql:8
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: restaurantdb
      MYSQL_USER: restaurant_user
      MYSQL_PASSWORD: restaurant_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - microservice-net

  mongodb:
    image: mongo:6
    container_name: mongodb-container
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - microservice-net

volumes:
  mysql_data:
  mongo_data:

networks:
  microservice-net:
    driver: bridge











