server:
  port: 8080

spring:
  application:
    name: gateway-service
  main:
    web-application-type: reactive
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: menu-service
              uri: http://localhost:8081
              predicates:
                - Path=/menu/**

            - id: restaurant-service
              uri: http://localhost:8082
              predicates:
                - Path=/restaurants/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
